name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main
      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    permissions:
      packages: write  # Allows writing to the GitHub Container Registry (GHCR)
      contents: read   # Allows reading repository contents (default for most workflows)

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/sjgorey/httpd-project:latest .

      # Push the Docker image to GHCR
      - name: Push Docker Image
        run: |
          docker push ghcr.io/sjgorey/httpd-project:latest
